create table if not exists public.tri_ai_usage_events (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('install', 'ip', 'global')),
  subject_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.tri_ai_usage_events enable row level security;

revoke all on table public.tri_ai_usage_events from anon, authenticated;
revoke all on sequence public.tri_ai_usage_events_id_seq from anon, authenticated;

create index if not exists tri_ai_usage_events_scope_subject_created_idx
  on public.tri_ai_usage_events (scope, subject_hash, created_at desc);

create index if not exists tri_ai_usage_events_created_idx
  on public.tri_ai_usage_events (created_at desc);
